name: ForestBigTrees
main: com.minefit.XerxesTireIron.ForestBigTrees.ForestBigTrees
version: 1.0
website: http://www.minefit.com
author: XerxesTireIron
description: Alter biome generation to include big trees in Forest and Forest Hills again.
load: startup